### ISSUE TITLE
AttributeError: 'YOLO' object has no attribute 'model_path'

### ISSUE THREAD

**Issue by giangnguyen2412** [ErrEss/PedestrianDetection#1]
Using TensorFlow backend.
2019-01-26 22:13:33.399940: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "yolo.py", line 216, in <module>
    detect_img(YOLO())
  File "yolo.py", line 32, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "yolo.py", line 49, in generate
    model_path = os.path.expanduser(self.model_path)
AttributeError: 'YOLO' object has no attribute 'model_path'

**Comment by Skyy93** [comment]
you are getting this error because in line 22 of the yolo.py the model_path is commented out

`#        self.model_path = 'model_data/yolo_weights.h5' # model path or trained weights path`
